name: Playwright API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install Playwright browsers
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Step 5: Run API tests
      - name: Run Playwright Tests
        run: npx playwright test

      # Step 6: Upload HTML report (optional but industry standard)
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report